package texlab.diagnostics

enum class ErrorCode {
    BIBTEX_MISSING_BEGIN_BRACE,
    BIBTEX_MISSING_ENTRY_NAME,
    BIBTEX_MISSING_COMMA,
    BIBTEX_MISSING_END_BRACE,
    BIBTEX_MISSING_ASSIGN,
    BIBTEX_MISSING_CONTENT,
    BIBTEX_MISSING_QUOTE,
}
