import * as factory from '../factory';
import { CompletionProvider } from '../provider';
import { LatexArgumentCompletionProvider } from './argument';

export const COLORS = [
  'black',
  'blue',
  'brown',
  'cyan',
  'darkgray',
  'gray',
  'green',
  'lightgray',
  'lime',
  'magenta',
  'olive',
  'orange',
  'pink',
  'purple',
  'red',
  'teal',
  'violet',
  'white',
  'yellow',
  'Apricot',
  'Bittersweet',
  'Blue',
  'BlueViolet',
  'Brown',
  'CadetBlue',
  'Cerulean',
  'Cyan',
  'DarkOrchid',
  'ForestGreen',
  'Goldenrod',
  'Green',
  'JungleGreen',
  'LimeGreen',
  'Mahogany',
  'Melon',
  'Mulberry',
  'OliveGreen',
  'OrangeRed',
  'Peach',
  'PineGreen',
  'ProcessBlue',
  'RawSienna',
  'RedOrange',
  'Rhodamine',
  'RoyalPurple',
  'Salmon',
  'Sepia',
  'SpringGreen',
  'TealBlue',
  'Turquoise',
  'VioletRed',
  'WildStrawberry',
  'YellowGreen',
  'Aquamarine',
  'Black',
  'BlueGreen',
  'BrickRed',
  'BurntOrange',
  'CarnationPink',
  'CornflowerBlue',
  'Dandelion',
  'Emerald',
  'Fuchsia',
  'Gray',
  'GreenYellow',
  'Lavender',
  'Magenta',
  'Maroon',
  'MidnightBlue',
  'NavyBlue',
  'Orange',
  'Orchid',
  'Periwinkle',
  'Plum',
  'Purple',
  'Red',
  'RedViolet',
  'RoyalBlue',
  'RubineRed',
  'SeaGreen',
  'SkyBlue',
  'Tan',
  'Thistle',
  'Violet',
  'White',
  'Yellow',
  'YellowOrange',
];

const ITEMS = COLORS.map(factory.createColor);

export const LatexColorCompletionProvider: CompletionProvider = LatexArgumentCompletionProvider(
  {
    commandNames: [
      '\\color',
      '\\colorbox',
      '\\textcolor',
      '\\pagecolor',
      '\\colorlet',
      '\\definespotcolor',
    ],
    argumentIndex: 0,
    execute: async () => ITEMS,
  },
);
