[package]
name = "line-index"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rustc-hash.workspace = true
text-size = "1.1.1"

[lib]
doctest = false
